name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add clippy as a component
      run: rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Check code style
      run: cargo fmt --all -- --check
    - name: Run tests
      run: cargo test --verbose
    - name: Linting code
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

